# Generated by Django 5.0.6 on 2024-09-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='visitors',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='visitors',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
